# Generated by Django 3.0.2 on 2020-01-31 01:41

from django.db import migrations, models
import interview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=interview.models.Question, to='interview.Question')),
                ('user', models.ForeignKey(on_delete=interview.models.User, to='interview.User')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('finish_datetime', models.DateTimeField(null=True)),
                ('submitted_questions', models.CharField(default='', max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=interview.models.Company, to='interview.Company')),
                ('user', models.ForeignKey(on_delete=interview.models.User, to='interview.User')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=interview.models.Company, to='interview.Company')),
                ('question', models.ForeignKey(on_delete=interview.models.Question, to='interview.Question')),
            ],
        ),
    ]
