# Generated by Django 3.0.2 on 2020-02-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20200131_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lasting_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
