# Generated by Django 3.0.2 on 2020-02-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_quiz_lasting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='lasting_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
