# Generated by Django 3.0.2 on 2020-02-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20200201_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='lasting_time',
            new_name='duration',
        ),
    ]
