# Generated by Django 3.0.2 on 2020-02-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20200201_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
